### PR TITLE
fix: fix backspace removing special chars and special chars styles

### LINKED ISSUE #35: Auto focus on "go back to logos"
People have been asking for the button "Go back to logos" to be automatically focused on popup. This would make the game much more friendly for desktop users.

### PR DESCRIPTION
**Pull request by edgargonzalez525**
fix backspace issues when there are special chars on the logo and auto-focus modal buttons.

closes #35 and #38

### CODE REVIEW

File: apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx [hunk 1]
```diff
@@ -172,23 +172,29 @@ class LogoVerify extends React.Component<LogoVerifyProps, LogoVerifyState> {
...
         map[letter.id]()
       ) : (
         <button
-          className={`logo-verify__guess-btn ${
-            this.showGuessAsWrong() ? 'logo-verify__guess-btn--wrong' : ''
-          } ${this.state.loadingGuess === idx ? 'logo-verify__guess-btn--loading' : ''} ${
-            this.isVerified() ? 'logo-verify__guess-btn--correct' : ''
-          }`}
+          className={`${btnClass}
+          ${this.state.loadingGuess === idx ? 'logo-verify__guess-btn--loading' : ''}`}
```
Comment (caroso1222) [inline apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx:197]: I think you can also put this conditional in your cool abstraction for `btnClass`

```javascript
const loadingClass = this.state.loadingGuess === idx ? 'logo-verify__guess-btn--loading' : '';
const btnClass = [defaultClass, wrongClass, correctClass, loadingClass].filter(Boolean).join(' ');
```

File: apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx [hunk 2]
```diff
@@ -235,39 +241,55 @@ class LogoVerify extends React.Component<LogoVerifyProps, LogoVerifyState> {
...
                 )}
-                <hr />
+                <hr/>
                 <Link
                   className="lv-modal__button lv-modal__button--prev"
                   to={`/levels/${this.props.logo.level}`}
+                  innerRef={node => {
+                    // `node` refers to the mounted DOM element
+                    // or null when unmounted
+                    if (node && isVerified) {
```
Comment (caroso1222) [inline apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx:287]: Just wondering, why do you put focus on the "Back to logos" element when the logo is verified? In the demo, this is causing the focus to be placed in the back to logos instead of "next logo".

File: apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx (hunk 1 above)
Comment (edgargonzalez525) [reply apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx:197]: hey Carlos, I didnt add that one because I didnt want the loading animation to be shown on the special chars, what do you think?

File: apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx (hunk 2 above)
Comment (edgargonzalez525) [reply apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx:287]: sorry, my idea was to place the focus on the back to logos button, when the next logo button was hidden, but I messed up the condition, it is fixed now

File: apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx (hunk 1 above)
Comment (caroso1222) [reply apps/logo-quiz/src/app/views/LogoVerify/LogoVerify.tsx:197]: Sounds good
